# Generated by Django 3.2.5 on 2024-11-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='min_puchase_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum puchase amount required to', max_digits=10, null=True),
        ),
    ]
