# Generated by Django 3.2.5 on 2024-11-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_coupon_min_puchase_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='min_puchase_amount',
            new_name='min_purchase_amount',
        ),
    ]
