# Generated by Django 3.2.5 on 2025-05-20 08:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20250517_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='attribute',
            name='affects_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productimages',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimages',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProductImageAttribute',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.attributevalue')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_attributes', to='product.productimages')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
