# Generated by Django 3.2.5 on 2025-05-31 16:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20250520_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='attributes',
        ),
        migrations.AddField(
            model_name='attribute',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productimageattribute',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='variantattribute',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productimageattribute',
            name='attribute_value',
            field=models.ForeignKey(limit_choices_to={'attribute__affects_image': True}, on_delete=django.db.models.deletion.CASCADE, related_name='image_attributes', to='product.attributevalue'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='variantattribute',
            name='attribute_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_attributes', to='product.attributevalue'),
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('attribute', 'value')},
        ),
        migrations.AlterUniqueTogether(
            name='productimageattribute',
            unique_together={('image', 'attribute_value')},
        ),
        migrations.AlterModelTable(
            name='attribute',
            table='attribute',
        ),
        migrations.AlterModelTable(
            name='attributevalue',
            table='attribute_value',
        ),
        migrations.AlterModelTable(
            name='brand',
            table='brand',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='productimageattribute',
            table='product_image_attribute',
        ),
        migrations.AlterModelTable(
            name='productimages',
            table='product_image',
        ),
        migrations.AlterModelTable(
            name='productvariant',
            table='variant',
        ),
        migrations.AlterModelTable(
            name='variantattribute',
            table='variant_attribute',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
    ]
