# Generated by Django 3.2.5 on 2025-06-09 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20250602_1812'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table=None,
        ),
        migrations.AlterModelTable(
            name='productvariant',
            table=None,
        ),
    ]
