# Generated by Django 3.2.5 on 2025-06-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20250609_2238'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='productvariant',
            table='variant',
        ),
    ]
