# Generated by Django 3.2.5 on 2025-05-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='accounts_profile',
        ),
    ]
