# Generated by Django 3.2.5 on 2025-01-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
