# Generated by Django 3.2.5 on 2024-03-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20240322_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Haryana', 'Haryana'), ('Goa', 'Goa'), ('Jharkhand', 'Jharkhand'), ('Kerala', 'Kerala'), ('Karnataka', 'Karnataka'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Chhattisgarh', 'Chhattisgarh'), ('Assam', 'Assam'), ('Andhra Pradesh', 'Andhra Pradesh')], max_length=100),
        ),
    ]
