# Generated by Django 3.2.5 on 2024-05-04 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Karnataka', 'Karnataka'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Chhattisgarh', 'Chhattisgarh'), ('Assam', 'Assam'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Kerala', 'Kerala'), ('Jharkhand', 'Jharkhand'), ('Haryana', 'Haryana'), ('Goa', 'Goa')], max_length=100),
        ),
    ]
