# Generated by Django 3.2.5 on 2024-06-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Kerala', 'Kerala'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Jharkhand', 'Jharkhand'), ('Chhattisgarh', 'Chhattisgarh'), ('Haryana', 'Haryana'), ('Karnataka', 'Karnataka'), ('Goa', 'Goa'), ('Assam', 'Assam')], max_length=100),
        ),
    ]
