# Generated by Django 3.2.5 on 2024-10-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Jharkhand', 'Jharkhand'), ('Chhattisgarh', 'Chhattisgarh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Haryana', 'Haryana'), ('Goa', 'Goa')], max_length=100),
        ),
    ]
