# Generated by Django 3.2.5 on 2024-10-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0007_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Goa', 'Goa'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Kerala', 'Kerala'), ('Haryana', 'Haryana'), ('Jharkhand', 'Jharkhand'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Chhattisgarh', 'Chhattisgarh'), ('Karnataka', 'Karnataka')], max_length=100),
        ),
    ]
