# Generated by Django 3.2.5 on 2024-10-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0008_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Chhattisgarh', 'Chhattisgarh'), ('Jharkhand', 'Jharkhand'), ('Haryana', 'Haryana'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Goa', 'Goa'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Karnataka', 'Karnataka'), ('Assam', 'Assam'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Kerala', 'Kerala')], max_length=100),
        ),
    ]
