# Generated by Django 3.2.5 on 2024-10-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0009_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Kerala', 'Kerala'), ('Karnataka', 'Karnataka'), ('Assam', 'Assam'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Haryana', 'Haryana'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa')], max_length=100),
        ),
    ]
