# Generated by Django 3.2.5 on 2024-11-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0010_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Himachal Pradesh', 'Himachal Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Jharkhand', 'Jharkhand'), ('Assam', 'Assam'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Haryana', 'Haryana')], max_length=100),
        ),
    ]
