# Generated by Django 3.2.5 on 2024-11-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0011_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Jharkhand', 'Jharkhand'), ('Kerala', 'Kerala'), ('Karnataka', 'Karnataka'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Goa', 'Goa'), ('Haryana', 'Haryana'), ('Chhattisgarh', 'Chhattisgarh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Assam', 'Assam'), ('Andhra Pradesh', 'Andhra Pradesh')], max_length=100),
        ),
    ]
