# Generated by Django 3.2.5 on 2024-11-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0012_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Goa', 'Goa'), ('Assam', 'Assam'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Haryana', 'Haryana'), ('Kerala', 'Kerala'), ('Karnataka', 'Karnataka'), ('Chhattisgarh', 'Chhattisgarh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Jharkhand', 'Jharkhand')], max_length=100),
        ),
    ]
