# Generated by Django 3.2.5 on 2025-01-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0013_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Jharkhand', 'Jharkhand'), ('Goa', 'Goa'), ('Assam', 'Assam'), ('Chhattisgarh', 'Chhattisgarh'), ('Haryana', 'Haryana'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Karnataka', 'Karnataka'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Kerala', 'Kerala')], max_length=100),
        ),
    ]
