# Generated by Django 3.2.5 on 2025-01-22 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0014_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Karnataka', 'Karnataka'), ('Goa', 'Goa'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Kerala', 'Kerala'), ('Assam', 'Assam'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Jharkhand', 'Jharkhand'), ('Chhattisgarh', 'Chhattisgarh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Haryana', 'Haryana')], max_length=100),
        ),
    ]
