# Generated by Django 3.2.5 on 2025-04-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0016_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Haryana', 'Haryana'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Karnataka', 'Karnataka'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Goa', 'Goa'), ('Maharashtra', 'Maharashtra'), ('Assam', 'Assam'), ('Manipur', 'Manipur'), ('Jharkhand', 'Jharkhand'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Meghalaya', 'Meghalaya'), ('Chhattisgarh', 'Chhattisgarh'), ('Bihar', 'Bihar'), ('Gujarat', 'Gujarat'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Kerala', 'Kerala')], max_length=100),
        ),
    ]
