# Generated by Django 3.2.5 on 2025-04-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0017_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Jharkhand', 'Jharkhand'), ('Goa', 'Goa'), ('Bihar', 'Bihar'), ('Maharashtra', 'Maharashtra'), ('Gujarat', 'Gujarat'), ('Chhattisgarh', 'Chhattisgarh'), ('Karnataka', 'Karnataka'), ('Manipur', 'Manipur'), ('Haryana', 'Haryana'), ('Meghalaya', 'Meghalaya'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Kerala', 'Kerala'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam')], max_length=100),
        ),
    ]
