# Generated by Django 3.2.5 on 2025-05-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0018_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Jharkhand', 'Jharkhand'), ('Assam', 'Assam'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Chhattisgarh', 'Chhattisgarh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Haryana', 'Haryana'), ('Goa', 'Goa'), ('Bihar', 'Bihar'), ('Manipur', 'Manipur'), ('Gujarat', 'Gujarat'), ('Kerala', 'Kerala'), ('Meghalaya', 'Meghalaya'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Maharashtra', 'Maharashtra'), ('Karnataka', 'Karnataka')], max_length=100),
        ),
    ]
