# Generated by Django 3.2.5 on 2025-05-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0019_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Jharkhand', 'Jharkhand'), ('Assam', 'Assam'), ('Chhattisgarh', 'Chhattisgarh'), ('Bihar', 'Bihar'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Maharashtra', 'Maharashtra'), ('Kerala', 'Kerala'), ('Meghalaya', 'Meghalaya'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Gujarat', 'Gujarat'), ('Goa', 'Goa'), ('Karnataka', 'Karnataka'), ('Haryana', 'Haryana'), ('Manipur', 'Manipur')], max_length=100),
        ),
    ]
