# Generated by Django 3.2.5 on 2025-05-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0020_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Chhattisgarh', 'Chhattisgarh'), ('Maharashtra', 'Maharashtra'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Meghalaya', 'Meghalaya'), ('Haryana', 'Haryana'), ('Goa', 'Goa'), ('Manipur', 'Manipur'), ('Gujarat', 'Gujarat'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Kerala', 'Kerala'), ('Karnataka', 'Karnataka'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Bihar', 'Bihar')], max_length=100),
        ),
    ]
