# Generated by Django 3.2.5 on 2025-05-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0022_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Maharashtra', 'Maharashtra'), ('Gujarat', 'Gujarat'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Goa', 'Goa'), ('Haryana', 'Haryana'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Chhattisgarh', 'Chhattisgarh'), ('Karnataka', 'Karnataka'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Bihar', 'Bihar'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Kerala', 'Kerala'), ('Assam', 'Assam'), ('Jharkhand', 'Jharkhand')], max_length=100),
        ),
    ]
