# Generated by Django 3.2.5 on 2025-05-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0023_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Arunachal Pradesh', 'Arunachal Pradesh'), ('Bihar', 'Bihar'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Meghalaya', 'Meghalaya'), ('Chhattisgarh', 'Chhattisgarh'), ('Gujarat', 'Gujarat'), ('Jharkhand', 'Jharkhand'), ('Assam', 'Assam'), ('Haryana', 'Haryana'), ('Maharashtra', 'Maharashtra'), ('Kerala', 'Kerala'), ('Manipur', 'Manipur'), ('Karnataka', 'Karnataka'), ('Goa', 'Goa')], max_length=100),
        ),
    ]
