# Generated by Django 3.2.5 on 2025-05-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0025_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Madhya Pradesh', 'Madhya Pradesh'), ('Kerala', 'Kerala'), ('Assam', 'Assam'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Manipur', 'Manipur'), ('Jharkhand', 'Jharkhand'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Chhattisgarh', 'Chhattisgarh'), ('Bihar', 'Bihar'), ('Maharashtra', 'Maharashtra'), ('Meghalaya', 'Meghalaya'), ('Gujarat', 'Gujarat'), ('Goa', 'Goa'), ('Karnataka', 'Karnataka'), ('Andhra Pradesh', 'Andhra Pradesh')], max_length=100),
        ),
    ]
