# Generated by Django 3.2.5 on 2025-06-01 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0026_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Kerala', 'Kerala'), ('Meghalaya', 'Meghalaya'), ('Jharkhand', 'Jharkhand'), ('Assam', 'Assam'), ('Chhattisgarh', 'Chhattisgarh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Gujarat', 'Gujarat'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Goa', 'Goa'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Karnataka', 'Karnataka'), ('Manipur', 'Manipur'), ('Maharashtra', 'Maharashtra'), ('Bihar', 'Bihar'), ('Haryana', 'Haryana')], max_length=100),
        ),
    ]
