# Generated by Django 3.2.5 on 2025-06-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0027_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Himachal Pradesh', 'Himachal Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Haryana', 'Haryana'), ('Karnataka', 'Karnataka'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Jharkhand', 'Jharkhand'), ('Kerala', 'Kerala'), ('Meghalaya', 'Meghalaya'), ('Maharashtra', 'Maharashtra'), ('Goa', 'Goa'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Bihar', 'Bihar'), ('Manipur', 'Manipur'), ('Gujarat', 'Gujarat'), ('Chhattisgarh', 'Chhattisgarh')], max_length=100),
        ),
    ]
