# Generated by Django 3.2.5 on 2025-06-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0028_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Arunachal Pradesh', 'Arunachal Pradesh'), ('Haryana', 'Haryana'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Gujarat', 'Gujarat'), ('Assam', 'Assam'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Manipur', 'Manipur'), ('Kerala', 'Kerala'), ('Chhattisgarh', 'Chhattisgarh'), ('Maharashtra', 'Maharashtra'), ('Meghalaya', 'Meghalaya'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Bihar', 'Bihar'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Goa', 'Goa')], max_length=100),
        ),
    ]
