# Generated by Django 3.2.5 on 2025-06-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0029_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Bihar', 'Bihar'), ('Manipur', 'Manipur'), ('Jharkhand', 'Jharkhand'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Meghalaya', 'Meghalaya'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Haryana', 'Haryana'), ('Chhattisgarh', 'Chhattisgarh'), ('Kerala', 'Kerala'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Goa', 'Goa'), ('Karnataka', 'Karnataka'), ('Maharashtra', 'Maharashtra'), ('Gujarat', 'Gujarat'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Assam', 'Assam')], max_length=100),
        ),
    ]
