# Generated by Django 3.2.5 on 2025-06-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0030_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Bihar', 'Bihar'), ('Goa', 'Goa'), ('Manipur', 'Manipur'), ('Haryana', 'Haryana'), ('Maharashtra', 'Maharashtra'), ('Karnataka', 'Karnataka'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Gujarat', 'Gujarat'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Jharkhand', 'Jharkhand'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Kerala', 'Kerala'), ('Chhattisgarh', 'Chhattisgarh'), ('Meghalaya', 'Meghalaya'), ('Himachal Pradesh', 'Himachal Pradesh')], max_length=100),
        ),
    ]
