# Generated by Django 3.2.5 on 2025-07-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0031_alter_address_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(choices=[('Jharkhand', 'Jharkhand'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Gujarat', 'Gujarat'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Chhattisgarh', 'Chhattisgarh'), ('Assam', 'Assam'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Haryana', 'Haryana'), ('Karnataka', 'Karnataka'), ('Meghalaya', 'Meghalaya'), ('Manipur', 'Manipur'), ('Goa', 'Goa'), ('Maharashtra', 'Maharashtra'), ('Kerala', 'Kerala'), ('Bihar', 'Bihar')], max_length=100),
        ),
    ]
