# Generated by Django 3.2.5 on 2024-10-25 09:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_is_deleted'),
        ('cart', '0006_auto_20241008_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='product',
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Pending', 'Pending')], default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('orders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.orderplaced')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='product',
            field=models.ManyToManyField(through='cart.OrderProduct', to='product.Product'),
        ),
    ]
