# Generated by Django 3.2.5 on 2024-10-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20241025_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='order_amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
