# Generated by Django 3.2.5 on 2025-04-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_auto_20241029_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('packed', 'Packed'), ('on the way', 'On the way'), ('delivered', 'Delivered'), ('canceled', 'Canceled')], default='pending', max_length=50),
        ),
    ]
